import artwork from "./art";
import icons from "./icons";
export default [
  {
    img: icons.icon1,
    name: "Jonathan Joestar",
    part: "Phantom Blood",
    rol: "protagonist",
    artwork: artwork.img1,
  },
  {
    img: icons.icon2,
    name: "William Zeppeli",
    part: "Phantom Blood",
    rol: "ally",
    artwork: artwork.img2,
  },
  {
    img: icons.icon3,
    name: "Speedwagon",
    part: "Phantom Blood",
    rol: "ally",
    artwork: artwork.img3,
  },
  {
    img: icons.icon4,
    name: "Dio Brando",
    part: "Phantom Blood",
    rol: "antagonist",
    artwork: artwork.img4,
  },
  {
    img: icons.icon5,
    name: "Joshep Joestar",
    part: "Battle Tendency",
    rol: "protagonist",
    artwork: artwork.img5,
  },
  {
    img: icons.icon6,
    name: "Caesar Zeppeli",
    part: "Battle Tendency",
    rol: "ally",
    artwork: artwork.img6,
  },
  {
    img: icons.icon7,
    name: "Lisa Lisa",
    part: "Battle Tendency",
    rol: "ally",
    artwork: artwork.img7,
  },
  {
    img: icons.icon8,
    name: "Esidisi",
    part: "Battle Tendency",
    rol: "antagonist",
    artwork: artwork.img8,
  },
  {
    img: icons.icon9,
    name: "Wamuu",
    part: "Battle Tendency",
    rol: "antagonist",
    artwork: artwork.img9,
  },
  {
    img: icons.icon10,
    name: "Kars",
    part: "Battle Tendency",
    rol: "antagonist",
    artwork: artwork.img10,
  },
  {
    img: icons.icon11,
    name: "Jotaro",
    part: "Stardust Crusader",
    rol: "protagonist",
    artwork: artwork.img11,
  },
  {
    img: icons.icon12,
    name: "Kakyoin",
    part: "Stardust Crusader",
    rol: "ally",
    artwork: artwork.img12,
  },
  {
    img: icons.icon13,
    name: "Muhammad Avdol",
    part: "Stardust Crusader",
    rol: "ally",
    artwork: artwork.img13,
  },
  {
    img: icons.icon14,
    name: "Polnareff",
    part: "Stardust Crusader",
    rol: "ally",
    artwork: artwork.img14,
  },
  {
    img: icons.icon15,
    name: "Joshep Joestar",
    part: "Stardust Crusader",
    rol: "ally",
    artwork: artwork.img15,
  },
  {
    img: icons.icon16,
    name: "Iggy",
    part: "Stardust Crusader",
    rol: "ally",
    artwork: artwork.img16,
  },
  {
    img: icons.icon17,
    name: "Hol Horse",
    part: "Stardust Crusader",
    rol: "enemy",
    artwork: artwork.img17,
  },
  {
    img: icons.icon18,
    name: "Vanilla",
    part: "Stardust Crusader",
    rol: "enemy",
    artwork: artwork.img18,
  }
];
