import artwork from "./art";
import icons from "./icons";
import parts from "./part"
export default [
  {
    img: icons.icon1,
    name: "Jonathan Joestar",
    part: parts[0],
    rol: "protagonist",
    hamonuser: true,
    artwork: artwork.img1,
  },
  {
    img: icons.icon2,
    name: "William Zeppeli",
    part: parts[0],
    rol: "ally",
    hamonuser: true,
    artwork: artwork.img2,
  },
  {
    img: icons.icon3,
    name: "Speedwagon",
    part: parts[0],
    rol: "ally",
    artwork: artwork.img3,
  },
  {
    img: icons.icon4,
    name: "Dio Brando",
    part: parts[0],
    rol: "antagonist",
    vampire: true,
    artwork: artwork.img4,
  },
  {
    img: icons.icon5,
    name: "Joshep Joestar",
    part: parts[1],
    rol: "protagonist",
    hamonuser: true,
    artwork: artwork.img5,
  },
  {
    img: icons.icon6,
    name: "Caesar Zeppeli",
    part: parts[1],
    rol: "ally",
    hamonuser: true,
    artwork: artwork.img6,
  },
  {
    img: icons.icon7,
    name: "Lisa Lisa",
    part: parts[1],
    rol: "ally",
    hamonuser: true,
    artwork: artwork.img7,
  },
  {
    img: icons.icon8,
    name: "Esidisi",
    part: parts[1],
    rol: "antagonist",
    vampire: true,
    artwork: artwork.img8,
  },
  {
    img: icons.icon9,
    name: "Wamuu",
    part: parts[1],
    rol: "antagonist",
    vampire: true,
    artwork: artwork.img9,
  },
  {
    img: icons.icon10,
    name: "Kars",
    part: parts[1],
    rol: "antagonist",
    vampire: true,
    artwork: artwork.img10,
  },
  {
    img: icons.icon11,
    name: "Jotaro",
    part: parts[2],
    rol: "protagonist",
    standuser: true,
    artwork: artwork.img11,
  },
  {
    img: icons.icon12,
    name: "Kakyoin",
    part: parts[2],
    rol: "ally",
    standuser: true,
    artwork: artwork.img12,
  },
  {
    img: icons.icon13,
    name: "Muhammad Avdol",
    part: parts[2],
    rol: "ally",
    standuser: true,
    artwork: artwork.img13,
  },
  {
    img: icons.icon14,
    name: "Polnareff",
    part: parts[2],
    rol: "ally",
    standuser: true,
    artwork: artwork.img14,
  },
  {
    img: icons.icon15,
    name: "Joshep Joestar",
    part: parts[2],
    rol: "ally",
    standuser: true,
    hamonuser: true,
    artwork: artwork.img15,
  },
  {
    img: icons.icon16,
    name: "Iggy",
    part: parts[2],
    rol: "ally",
    standuser: true,
    artwork: artwork.img16,
  },
  {
    img: icons.icon17,
    name: "Hol Horse",
    part: parts[2],
    rol: "enemy",
    standuser: true,
    artwork: artwork.img17,
  },
  {
    img: icons.icon18,
    name: "Vanilla",
    part: parts[2],
    rol: "enemy",
    standuser: true,
    vampire: true,
    artwork: artwork.img18,
  },
  {
    img: icons.icon19,
    name: "DIO",
    part: parts[2],
    rol: "antagonist",
    standuser: true,
    vampire: true,
    artwork: artwork.img19,
  },  
  {
    img: icons.icon20,
    name: "Mariah",
    part: parts[2],
    rol: "enemy",
    standuser: true,
    artwork: artwork.img20,
  },
  {
    img: icons.icon21,
    name: "Pet Shop",
    part: parts[2],
    rol: "enemy",
    standuser: true,
    artwork: artwork.img21,
  },
  {
    img: icons.icon22,
    name: "Josuke Higashikata",
    part: parts[3],
    rol: "protagonist",
    standuser: true,
    artwork: artwork.img22,
  },
  {
    img: icons.icon23,
    name: "Okuyasu Nijimura",
    part: parts[3],
    rol: "ally",
    standuser: true,
    artwork: artwork.img23,
  },
  {
    img: icons.icon24,
    name: "Koichi Hirose",
    part: parts[3],
    rol: "ally",
    standuser: true,
    artwork: artwork.img24,
  },
  {
    img: icons.icon25,
    name: "Shigekiyo Yangu",
    part: parts[3],
    rol: "ally",
    standuser: true,
    artwork: artwork.img25,
  },
  {
    img: icons.icon26,
    name: "Rohan Kishibe",
    part: parts[3],
    rol: "ally",
    standuser: true,
    artwork: artwork.img26,
  },
  {
    img: icons.icon27,
    name: "Akira Otoishi",
    part: parts[3],
    rol: "enemy",
    standuser: true,
    artwork: artwork.img27,
  },
  {
    img: icons.icon28,
    name: "Kosaku Kawajiri",
    part: parts[3],
    rol: "antagonist",
    standuser: true,
    artwork: artwork.img28,
  },
  {
    img: icons.icon29,
    name: "Yoshikage Kira",
    part: parts[3],
    rol: "antagonist",
    standuser: true,
    artwork: artwork.img29
  },
  {
    img: icons.icon30,
    name: "Giorno Giovanna",
    part: parts[4],
    rol: "protagonist",
    standuser: true,
    artwork: artwork.img30
  },
  {
    img: icons.icon31,
    name: "Bruno Bucciarati",
    part: parts[4],
    rol: "ally",
    standuser: true,
    artwork: artwork.img31
  },
  {
    img: icons.icon32,
    name: "Guido Mista",
    part: parts[4],
    rol: "ally",
    standuser: true,
    artwork: artwork.img32
  },
  {
    img: icons.icon33,
    name: "Narancia Ghirga",
    part: parts[4],
    rol: "ally",
    standuser: true,
    artwork: artwork.img33
  },
  {
    img: icons.icon34,
    name: "Pannacotta Fugo",
    part: parts[4],
    rol: "ally",
    standuser: true,
    artwork: artwork.img34
  },
  {
    img: icons.icon35,
    name: "Diavolo",
    part: parts[4],
    rol: "antagonist",
    standuser: true,
    artwork: artwork.img35
  },
  {
    img: icons.icon36,
    name: "Jolyne Cujoh",
    part: parts[5],
    rol: "protagonist",
    standuser: true,
    artwork: artwork.img36
  },
  {
    img: icons.icon37,
    name: "Ermes Costello",
    part: parts[5],
    rol: "ally",
    standuser: true,
    artwork: artwork.img37
  },
  {
    img: icons.icon38,
    name: "Narciso Anasui",
    part: parts[5],
    rol: "ally",
    standuser: true,
    artwork: artwork.img38
  },
  {
    img: icons.icon39,
    name: "Enrico Pucci",
    part: parts[5],
    rol: "antagonist",
    standuser: true,
    artwork: artwork.img39
  },
  {
    img: icons.icon40,
    name: "Johnny Joestar",
    part: parts[6],
    rol: "protagonist",
    spinuser: true,
    standuser: true,
    artwork: artwork.img40
  },
  {
    img: icons.icon41,
    name: "Giro Zeppeli",
    part: parts[6],
    rol: "ally",
    spinuser: true,
    standuser: true,
    artwork: artwork.img41
  },
  {
    img: icons.icon42,
    name: "Funny Valentine",
    part: parts[6],
    rol: "antagonist",
    standuser: true,
    artwork: artwork.img42
  },
  {
    img: icons.icon43,
    name: "Diego Brando",
    part: parts[6],
    rol: "enemy",
    standuser: true,
    artwork: artwork.img43
  },
  {
    img: icons.icon44,
    name: "Josuke Higashikata",
    part: parts[7],
    rol: "protagonist",
    standuser: true,
    artwork: artwork.img44
  },
];