import artwork from "./art";
import icons from "./icons";
export default [
  {
    img: icons.icon1,
    name: "Jonathan Joestar",
    part: "Phantom Blood",
    rol: "protagonist",
    hamonuser: true,
    artwork: artwork.img1,
  },
  {
    img: icons.icon2,
    name: "William Zeppeli",
    part: "Phantom Blood",
    rol: "ally",
    hamonuser: true,
    artwork: artwork.img2,
  },
  {
    img: icons.icon3,
    name: "Speedwagon",
    part: "Phantom Blood",
    rol: "ally",
    artwork: artwork.img3,
  },
  {
    img: icons.icon4,
    name: "Dio Brando",
    part: "Phantom Blood",
    rol: "antagonist",
    vampire: true,
    artwork: artwork.img4,
  },
  {
    img: icons.icon5,
    name: "Joshep Joestar",
    part: "Battle Tendency",
    rol: "protagonist",
    hamonuser: true,
    artwork: artwork.img5,
  },
  {
    img: icons.icon6,
    name: "Caesar Zeppeli",
    part: "Battle Tendency",
    rol: "ally",
    hamonuser: true,
    artwork: artwork.img6,
  },
  {
    img: icons.icon7,
    name: "Lisa Lisa",
    part: "Battle Tendency",
    rol: "ally",
    hamonuser: true,
    artwork: artwork.img7,
  },
  {
    img: icons.icon8,
    name: "Esidisi",
    part: "Battle Tendency",
    rol: "antagonist",
    vampire: true,
    artwork: artwork.img8,
  },
  {
    img: icons.icon9,
    name: "Wamuu",
    part: "Battle Tendency",
    rol: "antagonist",
    vampire: true,
    artwork: artwork.img9,
  },
  {
    img: icons.icon10,
    name: "Kars",
    part: "Battle Tendency",
    rol: "antagonist",
    vampire: true,
    artwork: artwork.img10,
  },
  {
    img: icons.icon11,
    name: "Jotaro",
    part: "Stardust Crusader",
    rol: "protagonist",
    hamonuser: false,
    standuser: true,
    vampire: false,
    artwork: artwork.img11,
  },
  {
    img: icons.icon12,
    name: "Kakyoin",
    part: "Stardust Crusader",
    rol: "ally",
    standuser: true,
    artwork: artwork.img12,
  },
  {
    img: icons.icon13,
    name: "Muhammad Avdol",
    part: "Stardust Crusader",
    rol: "ally",
    standuser: true,
    artwork: artwork.img13,
  },
  {
    img: icons.icon14,
    name: "Polnareff",
    part: "Stardust Crusader",
    rol: "ally",
    standuser: true,
    artwork: artwork.img14,
  },
  {
    img: icons.icon15,
    name: "Joshep Joestar",
    part: "Stardust Crusader",
    rol: "ally",
    standuser: true,
    hamonuser: true,
    artwork: artwork.img15,
  },
  {
    img: icons.icon16,
    name: "Iggy",
    part: "Stardust Crusader",
    rol: "ally",
    standuser: true,
    artwork: artwork.img16,
  },
  {
    img: icons.icon17,
    name: "Hol Horse",
    part: "Stardust Crusader",
    rol: "enemy",
    standuser: true,
    artwork: artwork.img17,
  },
  {
    img: icons.icon18,
    name: "Vanilla",
    part: "Stardust Crusader",
    rol: "enemy",
    standuser: true,
    vampire: true,
    artwork: artwork.img18,
  },
  {
    img: icons.icon19,
    name: "DIO",
    part: "Stardust Crusader",
    rol: "antagonist",
    standuser: true,
    vampire: true,
    artwork: artwork.img19,
  },  
  {
    img: icons.icon20,
    name: "Mariah",
    part: "Stardust Crusader",
    rol: "enemy",
    standuser: true,
    artwork: artwork.img20,
  },
  {
    img: icons.icon21,
    name: "Pet Shop",
    part: "Stardust Crusader",
    rol: "enemy",
    standuser: true,
    artwork: artwork.img21,
  },
  {
    img: icons.icon22,
    name: "Josuke Higashikata",
    part: "Diamond Is Unbreakable",
    rol: "protagonist",
    standuser: true,
    artwork: artwork.img22,
  },
  {
    img: icons.icon23,
    name: "Okuyasu Nijimura",
    part: "Diamond Is Unbreakable",
    rol: "ally",
    standuser: true,
    artwork: artwork.img23,
  },
  {
    img: icons.icon24,
    name: "Koichi Hirose",
    part: "Diamond Is Unbreakable",
    rol: "ally",
    standuser: true,
    artwork: artwork.img24,
  },
  {
    img: icons.icon25,
    name: "Shigekiyo Yangu",
    part: "Diamond Is Unbreakable",
    rol: "ally",
    standuser: true,
    artwork: artwork.img25,
  },
  {
    img: icons.icon26,
    name: "Rohan Kishibe",
    part: "Diamond Is Unbreakable",
    rol: "ally",
    standuser: true,
    artwork: artwork.img26,
  },
  {
    img: icons.icon27,
    name: "Akira Otoishi",
    part: "Diamond Is Unbreakable",
    rol: "enemy",
    standuser: true,
    artwork: artwork.img27,
  },
  {
    img: icons.icon28,
    name: "Kosaku Kawajiri",
    part: "Diamond Is Unbreakable",
    rol: "antagonist",
    standuser: true,
    artwork: artwork.img28,
  },
  {
    img: icons.icon29,
    name: "Yoshikage Kira",
    part: "Diamond Is Unbreakable",
    rol: "antagonist",
    standuser: true,
    artwork: artwork.img29
  },
  
];
